import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  Locale _currentLocale = const Locale('en');

  Locale get currentLocale => _currentLocale;

  bool get isUrdu => _currentLocale.languageCode == 'ur';

  void toggleLanguage() {
    if (_currentLocale.languageCode == 'en') {
      _currentLocale = const Locale('ur');
    } else {
      _currentLocale = const Locale('en');
    }
    notifyListeners();
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'StitchHub',
      'find_tailor': 'Find Your Perfect Tailor',
      'search_hint': 'Search by name or specialty...',
      'my_orders': 'My Orders',
      'chat': 'Chat',
      'profile': 'Profile',
      'track_order': 'Track Order',
      'measurements': 'Measurements',
      'payment': 'Payment',
      'settings': 'Settings',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'order_details': 'Order Details',
      'price': 'Price',
      'status': 'Status',
      'date': 'Date',
      'start_cutting': 'Start Cutting',
      'start_stitching': 'Start Stitching',
      'start_quality_check': 'Start Quality Check',
      'order_ready': 'Ready for Pickup',
      'order_complete': 'Completed',
      'order_cancelled': 'Cancelled',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'in_progress': 'In Progress',
      'cutting': 'Cutting Fabric',
      'stitching': 'Stitching Suit',
      'quality_check': 'Quality Check',
      'budget': 'Budget',
      'sasta': 'Budget (Sasta)',
      'standard': 'Standard',
      'designer': 'Designer',
      // Home Screen Additions
      'quick_actions': 'Quick Actions',
      'appointments': 'Appointments',
      'view_or_book': 'View or book',
      'share_app': 'Share App',
      'invite_friends': 'Invite friends',
      'my_favorites': 'My Favorites',
      'saved_tailors': 'Saved tailors',
      'messages_title': 'Messages',
      'chat_with_tailors': 'Chat with tailors',
      'recent_orders': 'Recent Orders',
      'no_orders_yet': 'No orders yet',
      'place_first_order': 'Place your first order to get started',
      // Tailor Detail Additions
      'tailor_profile': 'Tailor Profile',
      'about': 'About',
      'services': 'Services',
      'reviews': 'Reviews',
      'book_appointment': 'Book Appointment',
      'place_order': 'Place Order',
      'specialties': 'Specialties',
      'location': 'Location',
      'contact': 'Contact',
      'call': 'Call',
      'work_samples': 'Work Samples',
      'share_my_details': 'Share My Details',
      'available_now': 'Available Now',
      'pricing': 'Pricing',
      'rating': 'Rating',
      'views': 'Views',
      'orders': 'Orders',
      'response': 'Response',
      // Tailor Home Additions
      'dashboard': 'Dashboard',
      'welcome_back': 'Welcome back,',
      'manage_orders_grow_business': 'Manage your orders and grow your business',
      'view_orders': 'View Orders',
      'manage_your_orders': 'Manage your orders',
      'approve_or_decline': 'Approve or decline',
      'add_customer': 'Add Customer',
      'add_customer_measurements': 'Add customer & measurements',
      'view_measurement_requests': 'View measurement requests',
      'chat_with_customers': 'Chat with customers',
      'orders_appear_here': 'Orders will appear here when customers place them',
      // Orders & Status Additions
      'error_loading_orders': 'Error Loading Orders',
      'retry': 'Retry',
      'total_price': 'Total Price',
      'order_date': 'Order Date',
      'rate_and_review': 'Rate & Review',
      'how_was_experience': 'How was your experience?',
      'write_review': 'Write a review (optional)',
      'cancel': 'Cancel',
      'submit': 'Submit',
      'thank_you_review': 'Thank you for your review!',
      'status_pending': 'Pending',
      'status_confirmed': 'Confirmed',
      'status_in_progress': 'In Progress',
      'status_cutting': 'Cutting',
      'status_stitching': 'Stitching',
      'status_quality_check': 'Quality Check',
      'status_ready': 'Ready',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      // Tailor Orders Additions
      'filter_orders': 'Filter Orders',
      'all_orders': 'All Orders',
      'accept_order': 'Accept',
      'reject_order': 'Reject',
      'confirm_order': 'Confirm Order',
      'sure_accept_order': 'Are you sure you want to accept this order?',
      'order_confirmed_success': 'Order confirmed successfully',
      'reject_order_title': 'Reject Order',
      'provide_reject_reason': 'Please provide a reason for rejecting this order:',
      'reason_for_rejection': 'Reason for rejection',
      'enter_reason': 'Enter reason...',
      'order_rejected': 'Order rejected',
      // Profile Additions
      'profile_image_updated': 'Profile image updated successfully!',
      'error_updating_image': 'Error updating image: ',
      'profile_updated': 'Profile updated successfully!',
      'full_name': 'Full Name',
      'enter_name': 'Please enter your name',
      'phone_number': 'Phone Number',
      'enter_phone': 'Please enter your phone number',
      'valid_phone': 'Please enter a valid phone number',
      'save': 'Save',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'manage_privacy': 'Manage your privacy settings',
      'help_support': 'Help & Support',
      'get_help': 'Get help and contact support',
      'app_version_info': 'App version and information',
      'about_stitchhub': 'About StitchHub',
      'version': 'Version:',
      'connect_tailors': 'Connect with local tailors for all your stitching needs.',
      'ok': 'OK',
      'sign_out': 'Sign Out',
      // Tailor Profile Additions
      'business_info': 'Business Information',
      'business_name': 'Business Name',
      'enter_business_name': 'Please enter your business name',
      'city': 'City',
      'enter_city': 'Please enter your city',
      'tap_select_city': 'Tap to select city',
      'expertise': 'Expertise (e.g., Suits, Dresses)',
      'base_pricing': 'Base Pricing (Starting from)',
      'description': 'Description',
      'tell_customers': 'Tell customers about your services...',
      'no_services_added': 'No services added yet',
    },
    'ur': {
      'app_title': 'سٹچ ہب',
      'find_tailor': 'اپنا بہترین درزی تلاش کریں',
      'search_hint': 'نام یا مہارت سے تلاش کریں...',
      'my_orders': 'میرے آرڈرز',
      'chat': 'چیٹ',
      'profile': 'پروفائل',
      'track_order': 'آرڈر ٹریک کریں',
      'measurements': 'ناپ',
      'payment': 'ادائیگی',
      'settings': 'ترتیبات',
      'logout': 'لاگ آؤٹ',
      'edit_profile': 'پروفائل تبدیل کریں',
      'order_details': 'آرڈر کی تفصیلات',
      'price': 'قیمت',
      'status': 'حالت',
      'date': 'تاریخ',
      'start_cutting': 'کٹائی شروع کریں',
      'start_stitching': 'سلائی شروع کریں',
      'start_quality_check': 'کوالٹی چیک شروع کریں',
      'order_ready': 'وصولی کے لیے تیار',
      'order_complete': 'مکمل ہو گیا',
      'order_cancelled': 'منسوخ ہو گیا',
      'pending': 'زیر التواء',
      'confirmed': 'تصدیق شدہ',
      'in_progress': 'کام جاری ہے',
      'cutting': 'کٹائی ہو رہی ہے',
      'stitching': 'سلائی ہو رہی ہے',
      'quality_check': 'معیار کی جانچ',
      'budget': 'بجٹ',
      'sasta': 'سستا (بجٹ)',
      'standard': 'معیاری (اسٹینڈرڈ)',
      'designer': 'ڈیزائنر (پریمیم)',
      // Home Screen Additions
      'quick_actions': 'فوری کام',
      'appointments': 'ملاقاتیں',
      'view_or_book': 'دیکھیں یا بک کریں',
      'share_app': 'ایپ شیئر کریں',
      'invite_friends': 'دوستوں کو بلائیں',
      'my_favorites': 'میرے پسندیدہ',
      'saved_tailors': 'محفوظ درزی',
      'messages_title': 'پیغامات',
      'chat_with_tailors': 'درزیوں سے بات کریں',
      'recent_orders': 'حالیہ آرڈرز',
      'no_orders_yet': 'ابھی کوئی آرڈر نہیں',
      'place_first_order': 'آغاز کے لیے اپنا پہلا آرڈر دیں',
      // Tailor Detail Additions
      'tailor_profile': 'درزی کی پروفائل',
      'about': 'تفصیل',
      'services': 'خدمات',
      'reviews': 'جائزے',
      'book_appointment': 'وقت بک کریں',
      'place_order': 'آرڈر دیں',
      'specialties': 'مہارتیں',
      'location': 'مقام',
      'contact': 'رابطہ',
      'call': 'کال کریں',
      'work_samples': 'کام کے نمونے',
      'share_my_details': 'میری تفصیلات شیئر کریں',
      'available_now': 'دستیاب ہے',
      'pricing': 'قیمتیں',
      'rating': 'ریٹنگ',
      'views': 'مناظر',
      'orders': 'آرڈرز',
      'response': 'جواب',
      // Tailor Home Additions
      'dashboard': 'ڈیش بورڈ',
      'welcome_back': 'خوش آمدید،',
      'manage_orders_grow_business': 'اپنے آرڈرز سنبھالیں اور کاروبار بڑھائیں',
      'view_orders': 'آرڈرز دیکھیں',
      'manage_your_orders': 'اپنے آرڈرز کا انتظام کریں',
      'approve_or_decline': 'منظور یا مسترد کریں',
      'add_customer': 'کسٹمر شامل کریں',
      'add_customer_measurements': 'کسٹمر اور ناپ شامل کریں',
      'view_measurement_requests': 'ناپ کی درخواستیں دیکھیں',
      'chat_with_customers': 'کسٹمرز سے بات کریں',
      'orders_appear_here': 'کسٹمرز کے آرڈرز یہاں ظاہر ہوں گے',
      // Orders & Status Additions
      'error_loading_orders': 'آرڈرز لوڈ کرنے میں خرابی',
      'retry': 'دوبارہ کوشش کریں',
      'total_price': 'کل قیمت',
      'order_date': 'آرڈر کی تاریخ',
      'rate_and_review': 'ریٹ اور ریویو کریں',
      'how_was_experience': 'آپ کا تجربہ کیسا رہا؟',
      'write_review': 'ریویو لکھیں (اختیاری)',
      'cancel': 'منسوخ کریں',
      'submit': 'جمع کریں',
      'thank_you_review': 'آپ کے ریویو کا شکریہ!',
      'status_pending': 'زیر التوا',
      'status_confirmed': 'تصدیق شدہ',
      'status_in_progress': 'جاری ہے',
      'status_cutting': 'کٹائی',
      'status_stitching': 'سلائی',
      'status_quality_check': 'معیار کی جانچ',
      'status_ready': 'تیار ہے',
      'status_completed': 'مکمل ہو گیا',
      'status_cancelled': 'منسوخ ہو گیا',
      // Tailor Orders Additions
      'filter_orders': 'آرڈرز فلٹر کریں',
      'all_orders': 'تمام آرڈرز',
      'accept_order': 'قبول کریں',
      'reject_order': 'مسترد کریں',
      'confirm_order': 'آرڈر کی تصدیق کریں',
      'sure_accept_order': 'کیا آپ واقعی یہ آرڈر قبول کرنا چاہتے ہیں؟',
      'order_confirmed_success': 'آرڈر کامیابی سے کنفرم ہو گیا',
      'reject_order_title': 'آرڈر مسترد کریں',
      'provide_reject_reason': 'براہ کرم اس آرڈر کو مسترد کرنے کی وجہ بتائیں:',
      'reason_for_rejection': 'مسترد کرنے کی وجہ',
      'enter_reason': 'وجہ درج کریں...',
      'order_rejected': 'آرڈر مسترد کر دیا گیا',
      // Profile Additions
      'profile_image_updated': 'پروفائل کی تصویر کامیابی سے اپ ڈیٹ ہو گئی!',
      'error_updating_image': 'تصویر اپ ڈیٹ کرنے میں خرابی: ',
      'profile_updated': 'پروفائل کامیابی سے اپ ڈیٹ ہو گئی!',
      'full_name': 'پورا نام',
      'enter_name': 'براہ کرم اپنا نام درج کریں',
      'phone_number': 'فون نمبر',
      'enter_phone': 'براہ کرم اپنا فون نمبر درج کریں',
      'valid_phone': 'براہ کرم ایک درست فون نمبر درج کریں',
      'save': 'محفوظ کریں',
      'notifications': 'نوٹیفیکیشنز',
      'privacy': 'پرائیویسی',
      'manage_privacy': 'اپنی پرائیویسی کی ترتیبات کا نظم کریں',
      'help_support': 'مدد اور سپورٹ',
      'get_help': 'مدد حاصل کریں اور رابطہ کریں',
      'app_version_info': 'ایپ کا ورژن اور معلومات',
      'about_stitchhub': 'سٹچ ہب کے بارے میں',
      'version': 'ورژن:',
      'connect_tailors': 'اپنی سلائی کی تمام ضروریات کے لیے مقامی درزیوں سے رابطہ کریں۔',
      'ok': 'ٹھیک ہے',
      'sign_out': 'سائن آؤٹ کریں',
      // Tailor Profile Additions
      'business_info': 'کاروباری معلومات',
      'business_name': 'کاروبار کا نام',
      'enter_business_name': 'براہ کرم اپنے کاروبار کا نام درج کریں',
      'city': 'شہر',
      'enter_city': 'براہ کرم اپنا شہر درج کریں',
      'tap_select_city': 'شہر منتخب کرنے کے لیے تھپتھپائیں',
      'expertise': 'مہارت (مثلاً سوٹ، کپڑے)',
      'base_pricing': 'بنیادی قیمت (یہاں سے شروع ہوتی ہے)',
      'description': 'تفصیل',
      'tell_customers': 'صارفین کو اپنی خدمات کے بارے میں بتائیں...',
      'no_services_added': 'ابھی تک کوئی خدمات شامل نہیں کی گئیں',
    }
  };

  String translate(String key) {
    return _translations[_currentLocale.languageCode]?[key] ?? key;
  }
}
