import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'dart:io';
import '../../models/tailor_model.dart';
import '../../models/order_model.dart';
import '../../providers/order_provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/address_provider.dart';
import '../../models/address_model.dart';
import '../../theme/app_theme.dart';
import 'payment_screen.dart';

class PlaceOrderScreen extends StatefulWidget {
  final TailorModel tailor;

  const PlaceOrderScreen({
    super.key,
    required this.tailor,
  });

  @override
  State<PlaceOrderScreen> createState() => _PlaceOrderScreenState();
}

class _PlaceOrderScreenState extends State<PlaceOrderScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descriptionController = TextEditingController();
  final _notesController = TextEditingController();
  final _measurementsController = TextEditingController();
  
  String _selectedService = '';
  double _estimatedPrice = 0.0;
  List<File> _selectedImages = [];
  PaymentMethod _selectedPaymentMethod = PaymentMethod.cashOnDelivery;
  final ImagePicker _picker = ImagePicker();
  AddressModel? _selectedAddress;

  @override
  void initState() {
    super.initState();
    if (widget.tailor.services.isNotEmpty) {
      _selectedService = widget.tailor.services.first;
      _updatePrice();
    }
    // Load addresses
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final auth = Provider.of<AuthProvider>(context, listen: false);
      if (auth.user != null) {
        final addr = Provider.of<AddressProvider>(context, listen: false);
        await addr.loadAddresses(auth.user!.id);
        setState(() {
          _selectedAddress = addr.selectedAddress;
        });
      }
    });
  }

  @override
  void dispose() {
    _descriptionController.dispose();
    _notesController.dispose();
    _measurementsController.dispose();
    super.dispose();
  }

  void _updatePrice() {
    if (widget.tailor.pricing.containsKey(_selectedService.toLowerCase())) {
      setState(() {
        _estimatedPrice = widget.tailor.pricing[_selectedService.toLowerCase()]!;
      });
    }
  }

  Future<void> _pickImages() async {
    try {
      final List<XFile> images = await _picker.pickMultiImage();
      if (!mounted) return;
      setState(() {
        _selectedImages = images.map((image) => File(image.path)).toList();
      });
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error picking images: $e'),
          backgroundColor: AppTheme.error,
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
          ),
        ),
      );
    }
  }

  Future<void> _placeOrder() async {
    if (_formKey.currentState!.validate() && _selectedService.isNotEmpty) {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final orderProvider = Provider.of<OrderProvider>(context, listen: false);

      if (authProvider.user == null) return;

     
      final List<String> imageUrls = [];

      final order = OrderModel(
        id: '', // Will be generated by the service
        customerId: authProvider.user!.id,
        tailorId: widget.tailor.id,
        customerName: authProvider.user!.name,
        tailorName: widget.tailor.name,
        serviceType: _selectedService,
        description: _descriptionController.text,
        images: imageUrls,
        measurements: {
          'custom': _measurementsController.text,
        },
        price: _estimatedPrice,
        status: OrderStatus.pending,
        paymentStatus: PaymentStatus.pending,
        paymentMethod: _selectedPaymentMethod,
        orderDate: DateTime.now(),
        notes: _notesController.text,
        customerAddress: _selectedAddress != null
            ? '${_selectedAddress!.label}: ${_selectedAddress!.addressLine1}, ${_selectedAddress!.city}'
            : null,
        
        tailorAddress: widget.tailor.businessAddress,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // If wallet payment, create order first then navigate to payment screen
      if (_selectedPaymentMethod == PaymentMethod.wallet) {
        // Create order with pending payment
        final createdOrder = await orderProvider.createOrder(order);
        
        if (mounted && createdOrder != null) {
          // Navigate to payment screen
          final result = await Navigator.of(context).push(
            MaterialPageRoute(
              builder: (context) => PaymentScreen(
                orderId: createdOrder.id,
                amount: _estimatedPrice,
                orderDescription: _descriptionController.text.isNotEmpty
                    ? _descriptionController.text
                    : _selectedService,
              ),
            ),
          );

          if (!mounted) return;
          
          if (result != null && result['success'] == true) {
            Navigator.of(context).pop();
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: const Text('Order placed and payment completed successfully!'),
                backgroundColor: AppTheme.success,
                behavior: SnackBarBehavior.floating,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
                ),
              ),
            );
          } else {
            Navigator.of(context).pop();
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: const Text('Order placed. You can complete payment later.'),
                backgroundColor: AppTheme.warning,
                behavior: SnackBarBehavior.floating,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
                ),
              ),
            );
          }
        }
      } else {
        await orderProvider.createOrder(order);

        if (mounted) {
          Navigator.of(context).pop();
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const Text('Order placed successfully!'),
              backgroundColor: AppTheme.success,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
              ),
            ),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.gray50,
      appBar: AppBar(
        title: const Text('Place Order'),
        elevation: 0,
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppTheme.spacing16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Tailor Info Card
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Row(
                    children: [
                      CircleAvatar(
                        radius: 25,
                        backgroundImage: widget.tailor.profileImageUrl != null
                            ? NetworkImage(widget.tailor.profileImageUrl!)
                            : null,
                        child: widget.tailor.profileImageUrl == null
                            ? const Icon(Icons.person)
                            : null,
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              widget.tailor.businessName ?? widget.tailor.name,
                              style: const TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            Text(
                              widget.tailor.name,
                              style: const TextStyle(
                                color: Colors.grey,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              // Delivery Address
              const Text(
                'Delivery Address',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              Consumer<AddressProvider>(
                builder: (context, addrProvider, _) {
                  if (addrProvider.isLoading) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  if (addrProvider.addresses.isEmpty) {
                    return Row(
                      children: [
                        const Expanded(child: Text('No saved addresses')),
                        TextButton(
                          onPressed: () {
                            Navigator.of(context).push(
                              MaterialPageRoute(
                                builder: (_) => const _ManageAddressesScreen(),
                              ),
                            );
                          },
                          child: const Text('Add Address'),
                        )
                      ],
                    );
                  }
                  return Row(
                    children: [
                      Expanded(
                        child: DropdownButtonFormField<String>(
                          value: _selectedAddress?.id,
                          decoration: const InputDecoration(
                            border: OutlineInputBorder(),
                            hintText: 'Select delivery address',
                          ),
                          items: addrProvider.addresses
                              .map((a) => DropdownMenuItem(
                                    value: a.id,
                                    child: Text('${a.label}: ${a.addressLine1}'),
                                  ))
                              .toList(),
                          onChanged: (val) {
                            final a = addrProvider.addresses.firstWhere((e) => e.id == val);
                            setState(() {
                              _selectedAddress = a;
                            });
                          },
                        ),
                      ),
                      const SizedBox(width: 8),
                      IconButton(
                        icon: const Icon(Icons.edit_location_alt),
                        onPressed: () {
                          Navigator.of(context).push(
                            MaterialPageRoute(
                              builder: (_) => const _ManageAddressesScreen(),
                            ),
                          );
                        },
                      ),
                    ],
                  );
                },
              ),
              const SizedBox(height: 24),
              // Service Selection
              const Text(
                'Select Service',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              DropdownButtonFormField<String>(
                value: _selectedService.isEmpty ? null : _selectedService,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: 'Choose a service',
                ),
                items: widget.tailor.services.map((service) {
                  return DropdownMenuItem(
                    value: service,
                    child: Text(service),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedService = value!;
                    _updatePrice();
                  });
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please select a service';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),
              // Description
              const Text(
                'Description',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _descriptionController,
                maxLines: 3,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: 'Describe what you want to be stitched...',
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please provide a description';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),
              // Measurements
              const Text(
                'Measurements',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _measurementsController,
                maxLines: 2,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: 'Enter your measurements (chest, waist, etc.)',
                ),
              ),
              const SizedBox(height: 24),
              // Images
              const Text(
                'Reference Images',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              if (_selectedImages.isEmpty)
                Container(
                  width: double.infinity,
                  height: 120,
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: InkWell(
                    onTap: _pickImages,
                    child: const Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.add_photo_alternate,
                          size: 40,
                          color: Colors.grey,
                        ),
                        SizedBox(height: 8),
                        Text(
                          'Tap to add images',
                          style: TextStyle(color: Colors.grey),
                        ),
                      ],
                    ),
                  ),
                )
              else
                SizedBox(
                  height: 120,
                  child: ListView.builder(
                    scrollDirection: Axis.horizontal,
                    itemCount: _selectedImages.length + 1,
                    itemBuilder: (context, index) {
                      if (index == _selectedImages.length) {
                        return Container(
                          width: 120,
                          margin: const EdgeInsets.only(left: 8),
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: InkWell(
                            onTap: _pickImages,
                            child: const Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.add, color: Colors.grey),
                                Text('Add More', style: TextStyle(color: Colors.grey)),
                              ],
                            ),
                          ),
                        );
                      }
                      return Container(
                        width: 120,
                        margin: const EdgeInsets.only(right: 8),
                        child: Stack(
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(8),
                              child: Image.file(
                                _selectedImages[index],
                                width: 120,
                                height: 120,
                                fit: BoxFit.cover,
                              ),
                            ),
                            Positioned(
                              top: 4,
                              right: 4,
                              child: GestureDetector(
                                onTap: () {
                                  setState(() {
                                    _selectedImages.removeAt(index);
                                  });
                                },
                                child: Container(
                                  padding: const EdgeInsets.all(4),
                                  decoration: const BoxDecoration(
                                    color: Colors.red,
                                    shape: BoxShape.circle,
                                  ),
                                  child: const Icon(
                                    Icons.close,
                                    size: 16,
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                ),
              const SizedBox(height: 24),
              // Notes
              const Text(
                'Additional Notes',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _notesController,
                maxLines: 2,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: 'Any special instructions or requirements...',
                ),
              ),
              const SizedBox(height: 24),
              // Payment Method Selection
              const Text(
                'Payment Method',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              Card(
                child: Column(
                  children: [
                    RadioListTile<PaymentMethod>(
                      title: const Text('Cash on Delivery'),
                      subtitle: const Text('Pay when you receive your order'),
                      value: PaymentMethod.cashOnDelivery,
                      groupValue: _selectedPaymentMethod,
                      onChanged: (value) {
                        if (value != null) {
                          setState(() {
                            _selectedPaymentMethod = value;
                          });
                        }
                      },
                    ),
                    const Divider(height: 1),
                    RadioListTile<PaymentMethod>(
                      title: const Text('Wallet Transfer (JazzCash/EasyPaisa)'),
                      subtitle: const Text('Pay manually and upload receipt'),
                      value: PaymentMethod.wallet,
                      groupValue: _selectedPaymentMethod,
                      onChanged: (value) {
                        if (value != null) {
                          setState(() {
                            _selectedPaymentMethod = value;
                          });
                        }
                      },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
              // Price Summary
              Card(
                color: const Color(0xFF2E7D32),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Estimated Price:',
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.w500,
                              color: Colors.white,
                            ),
                          ),
                          Text(
                            'Rs. ${_estimatedPrice.toStringAsFixed(0)}',
                            style: const TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Final price may vary based on complexity',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.white.withValues(alpha: 0.8),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              // Place Order Button
              SizedBox(
                width: double.infinity,
                child: Consumer<OrderProvider>(
                  builder: (context, orderProvider, child) {
                    return ElevatedButton(
                      onPressed: orderProvider.isLoading ? null : _placeOrder,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: orderProvider.isLoading
                          ? const CircularProgressIndicator(color: Colors.white)
                          : const Text(
                              'Place Order',
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _ManageAddressesScreen extends StatelessWidget {
  const _ManageAddressesScreen();

  @override
  Widget build(BuildContext context) {
    final auth = Provider.of<AuthProvider>(context, listen: false);
    return Scaffold(
      appBar: AppBar(title: const Text('My Addresses')),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddOrEdit(context, auth.user!.id),
        child: const Icon(Icons.add),
      ),
      body: Consumer<AddressProvider>(
        builder: (context, provider, _) {
          if (provider.isLoading) {
            return const Center(child: CircularProgressIndicator());
          }
          if (provider.addresses.isEmpty) {
            return const Center(child: Text('No addresses added yet'));
          }
          return ListView.separated(
            padding: const EdgeInsets.all(16),
            itemCount: provider.addresses.length,
            separatorBuilder: (_, __) => const SizedBox(height: 12),
            itemBuilder: (_, i) {
              final a = provider.addresses[i];
              return Card(
                child: ListTile(
                  title: Text('${a.label} • ${a.addressLine1}'),
                  subtitle: Text('${a.city}, ${a.state}, ${a.country} - ${a.postalCode}'),
                  trailing: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      if (a.isDefault)
                        const Icon(Icons.check_circle, color: Colors.green),
                      IconButton(
                        icon: const Icon(Icons.edit),
                        onPressed: () => _showAddOrEdit(context, auth.user!.id, existing: a),
                      ),
                      IconButton(
                        icon: const Icon(Icons.delete, color: Colors.red),
                        onPressed: () => Provider.of<AddressProvider>(context, listen: false)
                            .deleteAddress(a.id),
                      ),
                    ],
                  ),
                  onTap: () => Provider.of<AddressProvider>(context, listen: false)
                      .setDefault(auth.user!.id, a.id),
                ),
              );
            },
          );
        },
      ),
    );
  }

  void _showAddOrEdit(BuildContext context, String userId, {AddressModel? existing}) {
    final formKey = GlobalKey<FormState>();
    final labelCtrl = TextEditingController(text: existing?.label ?? 'Home');
    final line1Ctrl = TextEditingController(text: existing?.addressLine1);
    final line2Ctrl = TextEditingController(text: existing?.addressLine2);
    final cityCtrl = TextEditingController(text: existing?.city);
    final stateCtrl = TextEditingController(text: existing?.state);
    final countryCtrl = TextEditingController(text: existing?.country ?? '');
    final postalCtrl = TextEditingController(text: existing?.postalCode);
    bool isDefault = existing?.isDefault ?? (existing == null);

    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: Text(existing == null ? 'Add Address' : 'Edit Address'),
        content: Form(
          key: formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextFormField(
                  controller: labelCtrl,
                  decoration: const InputDecoration(labelText: 'Label (Home, Work, etc.)'),
                  validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                ),
                TextFormField(
                  controller: line1Ctrl,
                  decoration: const InputDecoration(labelText: 'Address Line 1'),
                  validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                ),
                TextFormField(
                  controller: line2Ctrl,
                  decoration: const InputDecoration(labelText: 'Address Line 2 (optional)'),
                ),
                TextFormField(
                  controller: cityCtrl,
                  decoration: const InputDecoration(labelText: 'City'),
                  validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                ),
                TextFormField(
                  controller: stateCtrl,
                  decoration: const InputDecoration(labelText: 'State'),
                  validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                ),
                TextFormField(
                  controller: countryCtrl,
                  decoration: const InputDecoration(labelText: 'Country'),
                  validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                ),
                TextFormField(
                  controller: postalCtrl,
                  decoration: const InputDecoration(labelText: 'Postal Code'),
                  validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                ),
                const SizedBox(height: 8),
                SwitchListTile(
                  value: isDefault,
                  onChanged: (val) {
                    isDefault = val;
                  },
                  title: const Text('Set as default'),
                )
              ],
            ),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              if (!formKey.currentState!.validate()) return;
              final provider = Provider.of<AddressProvider>(context, listen: false);
              final model = AddressModel(
                id: existing?.id ?? '',
                userId: userId,
                label: labelCtrl.text.trim(),
                addressLine1: line1Ctrl.text.trim(),
                addressLine2: line2Ctrl.text.trim().isEmpty ? null : line2Ctrl.text.trim(),
                city: cityCtrl.text.trim(),
                state: stateCtrl.text.trim(),
                country: countryCtrl.text.trim(),
                postalCode: postalCtrl.text.trim(),
                latitude: null,
                longitude: null,
                isDefault: isDefault,
                createdAt: existing?.createdAt ?? DateTime.now(),
                updatedAt: DateTime.now(),
              );
              if (existing == null) {
                await provider.addAddress(model);
              } else {
                await provider.updateAddress(model);
              }
              if (context.mounted) Navigator.of(context).pop();
            },
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }
}



